### ISSUE TITLE
You can use the resize overlay and pass the enableDrag params

### ISSUE THREAD

**Issue by sunjiaming** [X-SLAYER/flutter_overlay_window#101]
You can use the resize overlay and pass the enableDrag params
```dart
await FlutterOverlayWindow.resizeOverlay(
                  WindowSize.matchParent,
                  (MediaQuery.of(context).size.height * 5).toInt(),
                  false, // here
                );
```

_Originally posted by @X-SLAYER in https://github.com/X-SLAYER/flutter_overlay_window/issues/64#issuecomment-1975236516_

**Comment by sunjiaming** [comment]
However, the latest version of the plug-in does not support setting this property

**Comment by X-SLAYER** [comment]
temporary fix here until i publish new versionnew fix here 

```yaml
  flutter_overlay_window:
    git:
      url: git@github.com:X-SLAYER/flutter_overlay_window.git
      ref: feature/overlay-improvements
```
