### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method close on channel x-slayer/overlay)

### ISSUE THREAD

**Issue by conank96** [X-SLAYER/flutter_overlay_window#18]
when using CloseOverlays has error this, are you can support fo me this issues?

**Comment by X-SLAYER** [comment]
Which version of the app are you using ?

**Comment by hemandroid** [comment]
Hi @X-SLAYER I'm also having the same issue, it's the latest version only.

**Comment by X-SLAYER** [comment]
Can you try to use the package like that and tell me? 

```yaml
  flutter_overlay_window:
    git:
      url: https://github.com/X-SLAYER/flutter_overlay_window.git
```

**Comment by hemandroid** [comment]
Hi @X-SLAYER I have used it as mentioned and it's working some how. I sent you an email with a query, can you please help me with that Iheb

**Comment by conank96** [comment]
> Can you try to use the package like that and tell me?
> 
> ```yaml
>   flutter_overlay_window:
>     git:
>       url: https://github.com/X-SLAYER/flutter_overlay_window.git
> ```

when i using example package of project be it working but i using lib in my project be it not working and has exception

**Comment by kmemo** [comment]
I have downloaded [tar.gz](https://pub.dev/packages/flutter_overlay_window/versions/0.3.2.tar.gz) file of your plugin ver 0.3.2 form [the versions page of your pulgin on pub.dev](https://pub.dev/packages/flutter_overlay_window/versions).

After un-archiving the file,

FlutterOverlayWindowPlugin.java is dated at 2022/07/13
home_page.dart is dated at 2022/07/16
These are in-consistent with the version information of the plugin and you have an old version of the plugin in the repository..

**Comment by kmemo** [comment]
@X-SLAYER 
I strongly believe that what on pub.dev is an old version of your pulgin and different from the latest version that has been uploaded here. Would you be able to double check the contents of 0.3.2.tar.gz file that is listed on the versions page of your pulgin on pub.dev?

**Comment by X-SLAYER** [comment]
yes, i already mentioned that you could use this until I publish a new version on the pub
```yaml
  flutter_overlay_window:
    git:
      url: https://github.com/X-SLAYER/flutter_overlay_window.git
      ref: FULL_SCREEN
```
