### ISSUE TITLE
MissingPluginException (MissingPluginException(No implementation found for method resizeOverlay on channel x-slayer/overlay))

### ISSUE THREAD

**Issue by abbas-25** [X-SLAYER/flutter_overlay_window#29]
Exception is thrown when at the last line of this code -

  ```
final status = await FlutterOverlayWindow.isPermissionGranted();

  if (status) {
    await FlutterOverlayWindow.showOverlay(
      alignment: OverlayAlignment.bottomCenter,
      overlayTitle: "Call Ended",
      visibility: NotificationVisibility.visibilitySecret,
      overlayContent: "Call ended with $number",
    );

    await FlutterOverlayWindow.resizeOverlay(80, 120);
```

Working with this dependency -
```
  flutter_overlay_window:
    git:
      url: https://github.com/X-SLAYER/flutter_overlay_window.git
      ref: FULL_SCREEN
```

**It has the same result on latest pub version**
