### ISSUE TITLE
MissingPluginException on close overlay / non-transparent clickthrough / overlay over system bars

### ISSUE THREAD

**Issue by Binj0** [X-SLAYER/flutter_overlay_window#40]
Hello, I have an issue and 2 questions.

The issue: On trying to close the overlay I get this error:
`E/flutter ( 5856): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method close on channel x-slayer/overlay)
E/flutter ( 5856): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
E/flutter ( 5856): <asynchronous suspension>
E/flutter ( 5856): #1      FlutterOverlayWindow.closeOverlay (package:flutter_overlay_window/flutter_overlay_window.dart:83:24)
E/flutter ( 5856): <asynchronous suspension>
E/flutter ( 5856): 
[log] Try to close
`
Question 1:
Is there a way to make the overlay, when set to clickthrough, non-transparent? Right now whenever I set it to clickthrough it becomes semi transparent.

Question 2:
Is there a way to overlay the content above the system navigation bar or statusbar? Right now I'm only able to position it as if there was a safe area around it.

Thank you in advance!

**Comment by mulaRahul** [comment]
Hey @Binj0, as mentioned in the #36 - 
> the package on pub.dev doesn't seem to be updated.

I also got the same issue and got it fixed using the git-branch directly. You can do the same, by adding the below in your **pubspec.yaml** -

```
dependencies:
  flutter:
    sdk: flutter

  flutter_overlay_window:
    git:
      url: https://github.com/X-SLAYER/flutter_overlay_window.git
      ref: main # use master branch
```

Hopefully, the maintainer will resolve the issue with pub.dev.


As for,
> Question 1: Is there a way to make the overlay, when set to clickthrough...

https://user-images.githubusercontent.com/96373135/210040287-826786fb-6dda-4adc-b41c-13cf3628746d.mp4

I have a solid overlay when using the `OverlayFlag.clickThrough` as seen above.

> Question 2: Is there a way to overlay the content above the system navigation...

I think that's enforced by the system (_as you shouldn't overlay on top of the system status/navigation bar_) but, I may be wrong 🤔.

**Comment by X-SLAYER** [comment]
yes i didin't update the latest version on pub.dev yet 

you can use the git version until I update it 

````yaml
 flutter_overlay_window:
     git:
      url: https://github.com/X-SLAYER/flutter_overlay_window.git

````
